Repository martin-georgiev/postgresql-for-doctrine, pull requests merged in 2021-11, with the labels that each got.

#98 Support DBAL v3
  composer.json
  tests/MartinGeorgiev/Doctrine/ORM/Query/AST/Functions/TestCase.php
Labels: enhancement

#99 Update QA tools
  ci/deptrac/config.yml
  ci/php-cs-fixer/config.php
  ci/phpstan/config.neon
  composer.json
  src/MartinGeorgiev/Doctrine/DBAL/Types/JsonTransformer.php
  src/MartinGeorgiev/Doctrine/DBAL/Types/JsonbArray.php
  tests/MartinGeorgiev/Doctrine/DBAL/Types/IntegerArrayTest.php
  tests/MartinGeorgiev/Doctrine/Fixtures/Entity/ContainsIntegers.php
  tests/MartinGeorgiev/Doctrine/Fixtures/Entity/ContainsJsons.php
  tests/MartinGeorgiev/Doctrine/Fixtures/Entity/ContainsTexts.php
  tests/MartinGeorgiev/Doctrine/Fixtures/Entity/Entity.php
Labels: enhancement, dependencies

#93 Add BooleanArray type
  src/MartinGeorgiev/Doctrine/DBAL/Types/BooleanArray.php
  tests/MartinGeorgiev/Doctrine/DBAL/Types/BooleanArrayTest.php
Labels: feature request

#102 Updated docs
  README.md
  docs/AVAILABLE-TYPES.md
  docs/INTEGRATING-WITH-DOCTRINE.md
  docs/INTEGRATING-WITH-LARAVEL.md
  docs/INTEGRATING-WITH-SYMFONY.md
Labels: dx
